commit: ## build and push container to docker hub| provide tag=(...)
	@docker build -t dmitryavdonin/otus-dz11-notification:latest . && docker push dmitryavdonin/otus-dz11-notification:latest
.PHONY: commit
