apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-app-config
data:
  APP_PORT: "{{ .Values.notification.port}}"
  APP_SERVICE_NAME: "notification_service"
  KAFKA_HOST: "my-cluster-kafka-bootstrap.kafka.svc.cluster.local"
  KAFKA_PORT: "9092"
  KAFKA_PAYMENT_STATUS_TOPIC: "payment-status"
  