apiVersion: v1
kind: Secret
metadata:
  name: notification-postgres-secret
type: Opaque
stringData:
  DB_HOST: app-notificationdb
  DB_DRIVER: postgres
  DB_USERNAME: {{ .Values.notificationdb.auth.username }}
  DB_PASSWORD: {{ .Values.notificationdb.auth.password }}
  DB_DBNAME: {{ .Values.notificationdb.auth.database }}
  DB_PORT: "5432"