apiVersion: v1
kind: Service
metadata:
  name: notification-app
  labels:
    app: notification-app
spec:
  selector:
    app: notification-app
  ports:
    - name: web
      port: 80
      targetPort: {{ .Values.notification.port}}
  type: ClusterIP
