commit: ## build and push container to docker hub| provide tag=(...)
	@docker build --pull --no-cache -t dmitryavdonin/otus-dz11-payment:latest . && docker push dmitryavdonin/otus-dz11-payment:latest
.PHONY: commit
